/** @type {import('tailwindcss').Config} */
const tailwindPreset = {
  theme: {
    extend: {
      colors: {
        primary: '#8A1B57',
        'primary-dark': '#6E1545',
        'primary-light': '#B23C7E',
        'primary-50': '#F8EAF1',
        gold: '#E0A93B',
        white: '#FFFFFF',
        background: '#FAFAFA',
        surface: '#FFFFFF',
        border: '#E5E5E5',
        'border-light': '#F0F0F0',
        text: '#1F2937',
        'text-secondary': '#4B5563',
        'text-muted': '#6B7280',
        'text-tertiary': '#9CA3AF',
        black: '#000000',
        overlay: 'rgba(0,0,0,0.5)',
        shimmer: '#E8E8E8',
        'shimmer-highlight': '#F5F5F5',
        success: '#16A34A',
        'success-light': '#DCFCE7',
        warning: '#F59E0B',
        'warning-light': '#FEF3C7',
        error: '#DC2626',
        'error-light': '#FEE2E2',
        info: '#2563EB',
        'info-light': '#DBEAFE',
      },
      spacing: {
        0: '0px',
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        3.5: '14px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        12: '48px',
        14: '56px',
        16: '64px',
        20: '80px',
        24: '96px',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '24px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        sansBold: ['Inter-Bold', 'Inter', 'system-ui', 'sans-serif'],
        sansSemibold: ['Inter-SemiBold', 'Inter', 'system-ui', 'sans-serif'],
        devanagari: ['Noto Sans Devanagari', 'sans-serif'],
      },
      fontSize: {
        xs: ['10px', '14px'],
        sm: ['12px', '16px'],
        base: ['14px', '20px'],
        md: ['16px', '22px'],
        lg: ['18px', '26px'],
        xl: ['20px', '28px'],
        '2xl': ['24px', '32px'],
        '3xl': ['28px', '38px'],
        '4xl': ['32px', '42px'],
        '5xl': ['40px', '52px'],
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgba(0,0,0,0.05)',
        md: '0 2px 4px 0 rgba(0,0,0,0.08)',
        lg: '0 4px 8px 0 rgba(0,0,0,0.10)',
        xl: '0 6px 12px 0 rgba(0,0,0,0.12)',
      },
      zIndex: {
        base: '0',
        dropdown: '10',
        sticky: '20',
        navbar: '30',
        modal: '40',
        toast: '50',
        tooltip: '60',
      },
    },
  },
}

module.exports = { tailwindPreset }
