import type {
  Product,
  Category,
  Deal,
  Banner,
  Review,
  Order,
  Address,
  Notification,
  Conversation,
  Message,
  UserProfile,
  CartItem,
} from '@chinooz/types'

const now = new Date().toISOString()
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString()

export const categories: Category[] = [
  {
    id: 'cat-electronics',
    name: 'Electronics',
    slug: 'electronics',
    icon: '📱',
    parentId: null,
    productCount: 1240,
    children: [
      { id: 'cat-phones', name: 'Mobile Phones', slug: 'mobile-phones', icon: '📱', parentId: 'cat-electronics', productCount: 420 },
      { id: 'cat-laptops', name: 'Laptops', slug: 'laptops', icon: '💻', parentId: 'cat-electronics', productCount: 310 },
      { id: 'cat-audio', name: 'Audio', slug: 'audio', icon: '🎧', parentId: 'cat-electronics', productCount: 210 },
    ],
  },
  {
    id: 'cat-fashion',
    name: 'Fashion',
    slug: 'fashion',
    icon: '👗',
    parentId: null,
    productCount: 860,
    children: [
      { id: 'cat-mens', name: "Men's Wear", slug: 'mens-wear', icon: '👔', parentId: 'cat-fashion', productCount: 340 },
      { id: 'cat-womens', name: "Women's Wear", slug: 'womens-wear', icon: '👗', parentId: 'cat-fashion', productCount: 520 },
    ],
  },
  {
    id: 'cat-home',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    icon: '🏠',
    parentId: null,
    productCount: 640,
    children: [
      { id: 'cat-furniture', name: 'Furniture', slug: 'furniture', icon: '🛋️', parentId: 'cat-home', productCount: 180 },
      { id: 'cat-kitchen', name: 'Kitchen', slug: 'kitchen', icon: '🍳', parentId: 'cat-home', productCount: 260 },
    ],
  },
  {
    id: 'cat-beauty',
    name: 'Beauty & Health',
    slug: 'beauty-health',
    icon: '💄',
    parentId: null,
    productCount: 520,
  },
  {
    id: 'cat-grocery',
    name: 'Grocery',
    slug: 'grocery',
    icon: '🛒',
    parentId: null,
    productCount: 980,
    children: [
      { id: 'cat-snacks', name: 'Snacks & Munchies', slug: 'snacks', icon: '🍿', parentId: 'cat-grocery', productCount: 320 },
      { id: 'cat-beverages', name: 'Beverages', slug: 'beverages', icon: '🍵', parentId: 'cat-grocery', productCount: 240 },
    ],
  },
  {
    id: 'cat-sports',
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    icon: '⚽',
    parentId: null,
    productCount: 310,
  },
]

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Samsung Galaxy A55 5G',
    slug: 'samsung-galaxy-a55-5g',
    description: 'Experience the brilliance of the Galaxy A55 5G with a stunning 6.6" Super AMOLED display, 50MP OIS camera, and 5000mAh battery. Perfect for everyday use.',
    images: [
      { uri: 'https://picsum.photos/seed/a55/400/400', alt: 'Samsung Galaxy A55 front' },
      { uri: 'https://picsum.photos/seed/a55b/400/400', alt: 'Samsung Galaxy A55 back' },
    ],
    price: 45999,
    compareAtPrice: 52999,
    currency: 'NPR',
    rating: 4.5,
    reviewCount: 234,
    categoryId: 'cat-phones',
    sellerId: 'seller-1',
    sellerName: 'TechHub Nepal',
    stock: 'in_stock',
    variants: [
      { id: 'v-1a', name: 'Awesome Ice Blue 128GB', price: 45999, sku: 'SAM-A55-BLU-128', stock: 'in_stock', attributes: { color: 'Ice Blue', storage: '128GB' } },
      { id: 'v-1b', name: 'Awesome Navy 256GB', price: 52999, sku: 'SAM-A55-NAV-256', stock: 'low_stock', attributes: { color: 'Navy', storage: '256GB' } },
    ],
    tags: ['5G', 'Samsung', 'Best Seller'],
    createdAt: daysAgo(30),
  },
  {
    id: 'prod-2',
    name: 'Handmade Dhaka Topi',
    slug: 'dhaka-topi',
    description: 'Traditional Nepali Dhaka Topi handwoven by artisans from Tehrathum. A cultural symbol worn during festivals and formal occasions.',
    images: [{ uri: 'https://picsum.photos/seed/topi/400/400', alt: 'Dhaka Topi' }],
    price: 850,
    compareAtPrice: 1200,
    currency: 'NPR',
    rating: 4.8,
    reviewCount: 512,
    categoryId: 'cat-mens',
    sellerId: 'seller-2',
    sellerName: 'Nepal Handicrafts',
    stock: 'in_stock',
    variants: [
      { id: 'v-2a', name: 'Standard Red', price: 850, sku: 'TOP-RED-STD', stock: 'in_stock', attributes: { color: 'Red' } },
      { id: 'v-2b', name: 'Standard Blue', price: 850, sku: 'TOP-BLU-STD', stock: 'in_stock', attributes: { color: 'Blue' } },
    ],
    tags: ['Traditional', 'Handmade', 'Cultural'],
    createdAt: daysAgo(120),
  },
  {
    id: 'prod-3',
    name: 'Wai Wai Noodles (Pack of 40)',
    slug: 'wai-wai-noodles-40',
    description: 'Nepal\'s favorite instant noodles. Ready in 2 minutes. Original chicken flavour — a pantry staple across the country.',
    images: [{ uri: 'https://picsum.photos/seed/waiwai/400/400', alt: 'Wai Wai Noodles' }],
    price: 800,
    currency: 'NPR',
    rating: 4.6,
    reviewCount: 1893,
    categoryId: 'cat-snacks',
    sellerId: 'seller-3',
    sellerName: 'GroceryMart',
    stock: 'in_stock',
    variants: [],
    tags: ['Grocery', 'Popular', 'Bulk'],
    createdAt: daysAgo(365),
  },
  {
    id: 'prod-4',
    name: 'Pashmina Shawl — Grade A',
    slug: 'pashmina-shawl-grade-a',
    description: 'Luxurious 100% pure pashmina shawl from the highlands of Nepal. Incredibly soft and warm. 200cm × 70cm.',
    images: [
      { uri: 'https://picsum.photos/seed/pashmina/400/400', alt: 'Pashmina shawl' },
      { uri: 'https://picsum.photos/seed/pashmina2/400/400', alt: 'Pashmina detail' },
    ],
    price: 3500,
    compareAtPrice: 5000,
    currency: 'NPR',
    rating: 4.9,
    reviewCount: 876,
    categoryId: 'cat-womens',
    sellerId: 'seller-4',
    sellerName: 'Kathmandu Cashmere Co.',
    stock: 'in_stock',
    variants: [
      { id: 'v-4a', name: 'Natural Cream', price: 3500, sku: 'PASH-CRM-A', stock: 'in_stock', attributes: { color: 'Cream' } },
      { id: 'v-4b', name: 'Maroon', price: 3500, sku: 'PASH-MRN-A', stock: 'in_stock', attributes: { color: 'Maroon' } },
      { id: 'v-4c', name: 'Black', price: 3800, sku: 'PASH-BLK-A', stock: 'low_stock', attributes: { color: 'Black' } },
    ],
    tags: ['Premium', 'Handmade', 'Gift'],
    createdAt: daysAgo(90),
  },
  {
    id: 'prod-5',
    name: 'Daraz 10000mAh Power Bank',
    slug: 'powerbank-10000mah',
    description: 'Compact 10000mAh power bank with dual USB output. Charge your phone up to 3 times on the go.',
    images: [{ uri: 'https://picsum.photos/seed/powerbank/400/400', alt: 'Power bank' }],
    price: 1299,
    compareAtPrice: 1999,
    currency: 'NPR',
    rating: 4.2,
    reviewCount: 156,
    categoryId: 'cat-electronics',
    sellerId: 'seller-1',
    sellerName: 'TechHub Nepal',
    stock: 'in_stock',
    variants: [],
    tags: ['Electronics', 'Portable', 'Deal'],
    createdAt: daysAgo(45),
  },
  {
    id: 'prod-6',
    name: 'Masala Tea — Organic Himalayan',
    slug: 'masala-tea-organic',
    description: 'Premium organic masala tea sourced from the hills of Ilam. Rich aroma with cardamom, cinnamon, and ginger.',
    images: [{ uri: 'https://picsum.photos/seed/masala/400/400', alt: 'Masala tea' }],
    price: 450,
    currency: 'NPR',
    rating: 4.7,
    reviewCount: 342,
    categoryId: 'cat-beverages',
    sellerId: 'seller-5',
    sellerName: 'Ilam Tea House',
    stock: 'in_stock',
    variants: [
      { id: 'v-6a', name: '250g Pack', price: 450, sku: 'TEA-250', stock: 'in_stock', attributes: { weight: '250g' } },
      { id: 'v-6b', name: '500g Pack', price: 800, sku: 'TEA-500', stock: 'in_stock', attributes: { weight: '500g' } },
    ],
    tags: ['Organic', 'Nepali', 'Best Seller'],
    createdAt: daysAgo(200),
  },
  {
    id: 'prod-7',
    name: 'Wooden Mandala Wall Art',
    slug: 'wooden-mandala-wall-art',
    description: 'Hand-carved wooden mandala — 45cm diameter. Intricate Buddhist-inspired design made by Bhaktapur artisans.',
    images: [{ uri: 'https://picsum.photos/seed/mandala/400/400', alt: 'Mandala wall art' }],
    price: 4500,
    compareAtPrice: 6000,
    currency: 'NPR',
    rating: 4.9,
    reviewCount: 89,
    categoryId: 'cat-furniture',
    sellerId: 'seller-6',
    sellerName: 'Bhaktapur Woodcraft',
    stock: 'low_stock',
    variants: [],
    tags: ['Handmade', 'Decor', 'Premium'],
    createdAt: daysAgo(60),
  },
  {
    id: 'prod-8',
    name: 'Xiaomi Redmi Note 13 Pro',
    slug: 'redmi-note-13-pro',
    description: '200MP camera, 120Hz AMOLED display, 5100mAh battery. Flagship features at a mid-range price.',
    images: [{ uri: 'https://picsum.photos/seed/redmi/400/400', alt: 'Redmi Note 13 Pro' }],
    price: 32999,
    compareAtPrice: 38999,
    currency: 'NPR',
    rating: 4.4,
    reviewCount: 167,
    categoryId: 'cat-phones',
    sellerId: 'seller-1',
    sellerName: 'TechHub Nepal',
    stock: 'in_stock',
    variants: [
      { id: 'v-8a', name: 'Midnight Black 128GB', price: 32999, sku: 'RED-13P-BLK', stock: 'in_stock', attributes: { color: 'Black', storage: '128GB' } },
      { id: 'v-8b', name: 'Ocean Teal 256GB', price: 37999, sku: 'RED-13P-TEL', stock: 'in_stock', attributes: { color: 'Teal', storage: '256GB' } },
    ],
    tags: ['5G', 'Xiaomi', 'Camera'],
    createdAt: daysAgo(15),
  },
  {
    id: 'prod-9',
    name: 'Singing Bowl — Hand Hammered',
    slug: 'singing-bowl-hand-hammered',
    description: 'Traditional hand-hammered singing bowl from Patan. Produces deep, resonant tones for meditation and healing.',
    images: [{ uri: 'https://picsum.photos/seed/bowl/400/400', alt: 'Singing bowl' }],
    price: 2800,
    currency: 'NPR',
    rating: 4.8,
    reviewCount: 203,
    categoryId: 'cat-home',
    sellerId: 'seller-7',
    sellerName: 'Patan Metal Works',
    stock: 'in_stock',
    variants: [
      { id: 'v-9a', name: 'Small (12cm)', price: 2800, sku: 'BOWL-SM', stock: 'in_stock', attributes: { size: '12cm' } },
      { id: 'v-9b', name: 'Medium (18cm)', price: 4500, sku: 'BOWL-MD', stock: 'in_stock', attributes: { size: '18cm' } },
      { id: 'v-9c', name: 'Large (25cm)', price: 7200, sku: 'BOWL-LG', stock: 'low_stock', attributes: { size: '25cm' } },
    ],
    tags: ['Handmade', 'Meditation', 'Cultural'],
    createdAt: daysAgo(180),
  },
  {
    id: 'prod-10',
    name: 'Timur Chilli Powder (200g)',
    slug: 'timur-chilli-powder',
    description: 'Sichuan pepper (timur) from the mid-hills of Nepal. Unique numbing citrus flavour essential for Nepali cooking.',
    images: [{ uri: 'https://picsum.photos/seed/timur/400/400', alt: 'Timur powder' }],
    price: 280,
    currency: 'NPR',
    rating: 4.5,
    reviewCount: 128,
    categoryId: 'cat-grocery',
    sellerId: 'seller-5',
    sellerName: 'Ilam Tea House',
    stock: 'in_stock',
    variants: [],
    tags: ['Spice', 'Organic', 'Nepali'],
    createdAt: daysAgo(100),
  },
]

export const deals: Deal[] = [
  { id: 'deal-1', title: 'Dashain Mega Sale', description: 'Up to 30% off on electronics', discount: 30, discountType: 'percentage', productId: 'prod-1', startsAt: daysAgo(2), endsAt: daysAgo(-5), image: 'https://picsum.photos/seed/deal1/800/300' },
  { id: 'deal-2', title: 'Handicraft Festival', description: 'Flat NPR 500 off on pashmina', discount: 500, discountType: 'fixed', productId: 'prod-4', startsAt: daysAgo(1), endsAt: daysAgo(-3), image: 'https://picsum.photos/seed/deal2/800/300' },
  { id: 'deal-3', title: 'Grocery Bundle', description: 'Buy 2 get 1 free on Wai Wai', discount: 33, discountType: 'percentage', productId: 'prod-3', startsAt: daysAgo(0), endsAt: daysAgo(-7), image: 'https://picsum.photos/seed/deal3/800/300' },
  { id: 'deal-4', title: 'Phone Fest', description: 'Redmi Note 13 Pro — NPR 6000 off', discount: 6000, discountType: 'fixed', productId: 'prod-8', startsAt: daysAgo(0), endsAt: daysAgo(-2), image: 'https://picsum.photos/seed/deal4/800/300' },
]

export const banners: Banner[] = [
  { id: 'ban-1', title: 'Dashain Sale is Live!', subtitle: 'Up to 50% off across categories', image: 'https://picsum.photos/seed/banner1/1200/400', link: '/deals', active: true },
  { id: 'ban-2', title: 'New Arrivals', subtitle: 'Check out the latest electronics', image: 'https://picsum.photos/seed/banner2/1200/400', link: '/categories/electronics', active: true },
  { id: 'ban-3', title: 'Free Delivery', subtitle: 'On orders above NPR 2000', image: 'https://picsum.photos/seed/banner3/1200/400', active: true },
]

export const reviews: Review[] = [
  { id: 'rev-1', productId: 'prod-1', userId: 'u-1', userName: 'Suman Shrestha', rating: 5, title: 'Best phone for the price', body: 'Camera quality is amazing. Battery lasts 2 days easily. Highly recommend!', photos: ['https://picsum.photos/seed/rev1a/200/200', 'https://picsum.photos/seed/rev1b/200/200'], createdAt: daysAgo(10), helpful: 24 },
  { id: 'rev-2', productId: 'prod-1', userId: 'u-2', userName: 'Anita Gurung', rating: 4, body: 'Good phone but heats up a bit during gaming. Otherwise perfect.', createdAt: daysAgo(8), helpful: 12 },
  { id: 'rev-3', productId: 'prod-2', userId: 'u-3', userName: 'Ram Bahadur Thapa', rating: 5, title: 'Authentic quality', body: 'My grandfather loved this topi. The weaving is excellent — truly handmade.', photos: ['https://picsum.photos/seed/rev3a/200/200'], createdAt: daysAgo(45), helpful: 31 },
  { id: 'rev-4', productId: 'prod-4', userId: 'u-4', userName: 'Priya Maharjan', rating: 5, title: 'So soft!', body: 'Bought as a gift for my mother. She uses it every day. Worth every rupee.', createdAt: daysAgo(20), helpful: 18 },
  { id: 'rev-5', productId: 'prod-6', userId: 'u-5', userName: 'Karma Lama', rating: 4, body: 'Rich flavour. Reminds me of tea from my village. Will order again.', createdAt: daysAgo(15), helpful: 9 },
  { id: 'rev-6', productId: 'prod-1', userId: 'u-6', userName: 'Deepa Tamang', rating: 3, body: 'Decent phone for the price. Screen is great but speakers could be better.', createdAt: daysAgo(5), helpful: 4 },
  { id: 'rev-7', productId: 'prod-1', userId: 'u-7', userName: 'Rajesh Shrestha', rating: 5, title: 'Worth every rupee', body: 'Upgraded from A35. Night and day difference. The camera alone is worth it.', photos: ['https://picsum.photos/seed/rev7a/200/200', 'https://picsum.photos/seed/rev7b/200/200', 'https://picsum.photos/seed/rev7c/200/200'], createdAt: daysAgo(3), helpful: 7 },
]

export const addresses: Address[] = [
  { id: 'addr-1', label: 'Home', fullName: 'Ayush Chaudhary', phone: '+977-9841234567', line1: 'Baneshwor-10', line2: 'Near Shankar Dev Campus', city: 'Kathmandu', district: 'Kathmandu', province: 'Bagmati', postalCode: '44600', isDefault: true },
  { id: 'addr-2', label: 'Office', fullName: 'Ayush Chaudhary', phone: '+977-9841234567', line1: 'Thamel Marg', city: 'Kathmandu', district: 'Kathmandu', province: 'Bagmati', postalCode: '44600', isDefault: false },
]

export const orders: Order[] = [
  {
    id: 'ord-1',
    items: [
      { id: 'ci-1', productId: 'prod-1', variantId: 'v-1a', name: 'Samsung Galaxy A55 5G — Ice Blue 128GB', image: 'https://picsum.photos/seed/a55/400/400', price: 45999, quantity: 1, maxQuantity: 5 },
    ],
    total: 45999,
    currency: 'NPR',
    status: 'shipped',
    timeline: [
      { status: 'pending', timestamp: daysAgo(5) },
      { status: 'confirmed', timestamp: daysAgo(4) },
      { status: 'processing', timestamp: daysAgo(3) },
      { status: 'shipped', timestamp: daysAgo(1), note: 'Dispatched via Pathao' },
    ],
    address: addresses[0],
    createdAt: daysAgo(5),
    estimatedDelivery: daysAgo(-2),
  },
  {
    id: 'ord-2',
    items: [
      { id: 'ci-2', productId: 'prod-4', variantId: 'v-4a', name: 'Pashmina Shawl — Natural Cream', image: 'https://picsum.photos/seed/pashmina/400/400', price: 3500, quantity: 2, maxQuantity: 10 },
      { id: 'ci-3', productId: 'prod-6', variantId: 'v-6a', name: 'Masala Tea 250g', image: 'https://picsum.photos/seed/masala/400/400', price: 450, quantity: 3, maxQuantity: 20 },
    ],
    total: 8350,
    currency: 'NPR',
    status: 'delivered',
    timeline: [
      { status: 'pending', timestamp: daysAgo(20) },
      { status: 'confirmed', timestamp: daysAgo(19) },
      { status: 'processing', timestamp: daysAgo(18) },
      { status: 'shipped', timestamp: daysAgo(16) },
      { status: 'delivered', timestamp: daysAgo(14), note: 'Delivered to doorstep' },
    ],
    address: addresses[0],
    createdAt: daysAgo(20),
  },
]

export const notifications: Notification[] = [
  { id: 'notif-1', type: 'order', title: 'Order Shipped!', body: 'Your Samsung Galaxy A55 has been dispatched via Pathao.', read: false, createdAt: daysAgo(1), link: '/orders/ord-1' },
  { id: 'notif-2', type: 'promo', title: 'Dashain Sale 🎉', body: 'Up to 50% off on electronics. Limited time only!', read: false, createdAt: daysAgo(2), link: '/deals' },
  { id: 'notif-3', type: 'system', title: 'Welcome to Chinooz!', body: 'Explore thousands of products from local sellers.', read: true, createdAt: daysAgo(30) },
  { id: 'notif-4', type: 'message', title: 'New message from TechHub Nepal', body: 'Your warranty card has been uploaded.', read: true, createdAt: daysAgo(3) },
]

export const conversations: Conversation[] = [
  { id: 'conv-1', participantName: 'TechHub Nepal', lastMessage: 'Your warranty card has been uploaded.', lastMessageAt: daysAgo(3), unreadCount: 0 },
  { id: 'conv-2', participantName: 'Nepal Handicrafts', lastMessage: 'Thank you for your order! We will ship within 24 hours.', lastMessageAt: daysAgo(10), unreadCount: 0 },
  { id: 'conv-3', participantName: 'Chinooz Support', lastMessage: 'How can we help you today?', lastMessageAt: daysAgo(30), unreadCount: 1 },
]

export const messages: Message[] = [
  { id: 'msg-1', conversationId: 'conv-1', senderId: 'seller-1', senderName: 'TechHub Nepal', body: 'Hi! Your order has been confirmed.', createdAt: daysAgo(5), read: true },
  { id: 'msg-2', conversationId: 'conv-1', senderId: 'user-1', senderName: 'You', body: 'Great, when will it ship?', createdAt: daysAgo(4), read: true },
  { id: 'msg-3', conversationId: 'conv-1', senderId: 'seller-1', senderName: 'TechHub Nepal', body: 'Your warranty card has been uploaded.', createdAt: daysAgo(3), read: true },
  { id: 'msg-4', conversationId: 'conv-3', senderId: 'system', senderName: 'Chinooz Support', body: 'How can we help you today?', createdAt: daysAgo(30), read: false },
]

export const userProfile: UserProfile = {
  id: 'user-1',
  name: 'Ayush Chaudhary',
  email: 'ayush@example.com',
  phone: '+977-9841234567',
  defaultAddressId: 'addr-1',
  addresses,
}

export const sampleCartItems: CartItem[] = [
  { id: 'ci-s1', productId: 'prod-1', variantId: 'v-1a', name: 'Samsung Galaxy A55 5G — Ice Blue 128GB', image: 'https://picsum.photos/seed/a55/400/400', price: 45999, quantity: 1, maxQuantity: 5 },
  { id: 'ci-s2', productId: 'prod-4', variantId: 'v-4a', name: 'Pashmina Shawl — Natural Cream', image: 'https://picsum.photos/seed/pashmina/400/400', price: 3500, quantity: 2, maxQuantity: 10 },
  { id: 'ci-s3', productId: 'prod-6', variantId: 'v-6a', name: 'Masala Tea 250g', image: 'https://picsum.photos/seed/masala/400/400', price: 450, quantity: 1, maxQuantity: 20 },
]
