import type {
  Product,
  Category,
  Deal,
  Banner,
  Review,
  Order,
  Address,
  Notification,
  Conversation,
  Message,
  UserProfile,
  CartItem,
  SellerProduct,
} from '@chinooz/types'

const now = new Date().toISOString()
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString()

export const categories: Category[] = [
  {
    id: 'cat-electronics',
    name: 'Electronics',
    slug: 'electronics',
    icon: '📱',
    parentId: null,
    productCount: 1240,
    children: [
      { id: 'cat-phones', name: 'Mobile Phones', slug: 'mobile-phones', icon: '📱', parentId: 'cat-electronics', productCount: 420 },
      { id: 'cat-laptops', name: 'Laptops', slug: 'laptops', icon: '💻', parentId: 'cat-electronics', productCount: 310 },
      { id: 'cat-audio', name: 'Audio', slug: 'audio', icon: '🎧', parentId: 'cat-electronics', productCount: 210 },
    ],
  },
  {
    id: 'cat-fashion',
    name: 'Fashion',
    slug: 'fashion',
    icon: '👗',
    parentId: null,
    productCount: 860,
    children: [
      { id: 'cat-mens', name: "Men's Wear", slug: 'mens-wear', icon: '👔', parentId: 'cat-fashion', productCount: 340 },
      { id: 'cat-womens', name: "Women's Wear", slug: 'womens-wear', icon: '👗', parentId: 'cat-fashion', productCount: 520 },
    ],
  },
  {
    id: 'cat-home',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    icon: '🏠',
    parentId: null,
    productCount: 640,
    children: [
      { id: 'cat-furniture', name: 'Furniture', slug: 'furniture', icon: '🛋️', parentId: 'cat-home', productCount: 180 },
      { id: 'cat-kitchen', name: 'Kitchen', slug: 'kitchen', icon: '🍳', parentId: 'cat-home', productCount: 260 },
    ],
  },
  {
    id: 'cat-beauty',
    name: 'Beauty & Health',
    slug: 'beauty-health',
    icon: '💄',
    parentId: null,
    productCount: 520,
  },
  {
    id: 'cat-grocery',
    name: 'Grocery',
    slug: 'grocery',
    icon: '🛒',
    parentId: null,
    productCount: 980,
    children: [
      { id: 'cat-snacks', name: 'Snacks & Munchies', slug: 'snacks', icon: '🍿', parentId: 'cat-grocery', productCount: 320 },
      { id: 'cat-beverages', name: 'Beverages', slug: 'beverages', icon: '🍵', parentId: 'cat-grocery', productCount: 240 },
    ],
  },
  {
    id: 'cat-sports',
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    icon: '⚽',
    parentId: null,
    productCount: 310,
  },
]

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Samsung Galaxy A55 5G',
    slug: 'samsung-galaxy-a55-5g',
    description: 'Experience the brilliance of the Galaxy A55 5G with a stunning 6.6" Super AMOLED display, 50MP OIS camera, and 5000mAh battery. Perfect for everyday use.',
    images: [
      { uri: 'https://picsum.photos/seed/a55/400/400', alt: 'Samsung Galaxy A55 front' },
      { uri: 'https://picsum.photos/seed/a55b/400/400', alt: 'Samsung Galaxy A55 back' },
    ],
    price: 45999,
    compareAtPrice: 52999,
    currency: 'NPR',
    rating: 4.5,
    reviewCount: 234,
    categoryId: 'cat-phones',
    sellerId: 'seller-1',
    sellerName: 'TechHub Nepal',
    stock: 'in_stock',
    variants: [
      { id: 'v-1a', name: 'Awesome Ice Blue 128GB', price: 45999, sku: 'SAM-A55-BLU-128', stock: 'in_stock', attributes: { color: 'Ice Blue', storage: '128GB' } },
      { id: 'v-1b', name: 'Awesome Navy 256GB', price: 52999, sku: 'SAM-A55-NAV-256', stock: 'low_stock', attributes: { color: 'Navy', storage: '256GB' } },
    ],
    tags: ['5G', 'Samsung', 'Best Seller'],
    createdAt: daysAgo(30),
  },
  {
    id: 'prod-2',
    name: 'Handmade Dhaka Topi',
    slug: 'dhaka-topi',
    description: 'Traditional Nepali Dhaka Topi handwoven by artisans from Tehrathum. A cultural symbol worn during festivals and formal occasions.',
    images: [{ uri: 'https://picsum.photos/seed/topi/400/400', alt: 'Dhaka Topi' }],
    price: 850,
    compareAtPrice: 1200,
    currency: 'NPR',
    rating: 4.8,
    reviewCount: 512,
    categoryId: 'cat-mens',
    sellerId: 'seller-2',
    sellerName: 'Nepal Handicrafts',
    stock: 'in_stock',
    variants: [
      { id: 'v-2a', name: 'Standard Red', price: 850, sku: 'TOP-RED-STD', stock: 'in_stock', attributes: { color: 'Red' } },
      { id: 'v-2b', name: 'Standard Blue', price: 850, sku: 'TOP-BLU-STD', stock: 'in_stock', attributes: { color: 'Blue' } },
    ],
    tags: ['Traditional', 'Handmade', 'Cultural'],
    createdAt: daysAgo(120),
  },
  {
    id: 'prod-3',
    name: 'Wai Wai Noodles (Pack of 40)',
    slug: 'wai-wai-noodles-40',
    description: 'Nepal\'s favorite instant noodles. Ready in 2 minutes. Original chicken flavour — a pantry staple across the country.',
    images: [{ uri: 'https://picsum.photos/seed/waiwai/400/400', alt: 'Wai Wai Noodles' }],
    price: 800,
    currency: 'NPR',
    rating: 4.6,
    reviewCount: 1893,
    categoryId: 'cat-snacks',
    sellerId: 'seller-3',
    sellerName: 'GroceryMart',
    stock: 'in_stock',
    variants: [],
    tags: ['Grocery', 'Popular', 'Bulk'],
    createdAt: daysAgo(365),
  },
  {
    id: 'prod-4',
    name: 'Pashmina Shawl — Grade A',
    slug: 'pashmina-shawl-grade-a',
    description: 'Luxurious 100% pure pashmina shawl from the highlands of Nepal. Incredibly soft and warm. 200cm × 70cm.',
    images: [
      { uri: 'https://picsum.photos/seed/pashmina/400/400', alt: 'Pashmina shawl' },
      { uri: 'https://picsum.photos/seed/pashmina2/400/400', alt: 'Pashmina detail' },
    ],
    price: 3500,
    compareAtPrice: 5000,
    currency: 'NPR',
    rating: 4.9,
    reviewCount: 876,
    categoryId: 'cat-womens',
    sellerId: 'seller-4',
    sellerName: 'Kathmandu Cashmere Co.',
    stock: 'in_stock',
    variants: [
      { id: 'v-4a', name: 'Natural Cream', price: 3500, sku: 'PASH-CRM-A', stock: 'in_stock', attributes: { color: 'Cream' } },
      { id: 'v-4b', name: 'Maroon', price: 3500, sku: 'PASH-MRN-A', stock: 'in_stock', attributes: { color: 'Maroon' } },
      { id: 'v-4c', name: 'Black', price: 3800, sku: 'PASH-BLK-A', stock: 'low_stock', attributes: { color: 'Black' } },
    ],
    tags: ['Premium', 'Handmade', 'Gift'],
    createdAt: daysAgo(90),
  },
  {
    id: 'prod-5',
    name: 'Daraz 10000mAh Power Bank',
    slug: 'powerbank-10000mah',
    description: 'Compact 10000mAh power bank with dual USB output. Charge your phone up to 3 times on the go.',
    images: [{ uri: 'https://picsum.photos/seed/powerbank/400/400', alt: 'Power bank' }],
    price: 1299,
    compareAtPrice: 1999,
    currency: 'NPR',
    rating: 4.2,
    reviewCount: 156,
    categoryId: 'cat-electronics',
    sellerId: 'seller-1',
    sellerName: 'TechHub Nepal',
    stock: 'in_stock',
    variants: [],
    tags: ['Electronics', 'Portable', 'Deal'],
    createdAt: daysAgo(45),
  },
  {
    id: 'prod-6',
    name: 'Masala Tea — Organic Himalayan',
    slug: 'masala-tea-organic',
    description: 'Premium organic masala tea sourced from the hills of Ilam. Rich aroma with cardamom, cinnamon, and ginger.',
    images: [{ uri: 'https://picsum.photos/seed/masala/400/400', alt: 'Masala tea' }],
    price: 450,
    currency: 'NPR',
    rating: 4.7,
    reviewCount: 342,
    categoryId: 'cat-beverages',
    sellerId: 'seller-5',
    sellerName: 'Ilam Tea House',
    stock: 'in_stock',
    variants: [
      { id: 'v-6a', name: '250g Pack', price: 450, sku: 'TEA-250', stock: 'in_stock', attributes: { weight: '250g' } },
      { id: 'v-6b', name: '500g Pack', price: 800, sku: 'TEA-500', stock: 'in_stock', attributes: { weight: '500g' } },
    ],
    tags: ['Organic', 'Nepali', 'Best Seller'],
    createdAt: daysAgo(200),
  },
  {
    id: 'prod-7',
    name: 'Wooden Mandala Wall Art',
    slug: 'wooden-mandala-wall-art',
    description: 'Hand-carved wooden mandala — 45cm diameter. Intricate Buddhist-inspired design made by Bhaktapur artisans.',
    images: [{ uri: 'https://picsum.photos/seed/mandala/400/400', alt: 'Mandala wall art' }],
    price: 4500,
    compareAtPrice: 6000,
    currency: 'NPR',
    rating: 4.9,
    reviewCount: 89,
    categoryId: 'cat-furniture',
    sellerId: 'seller-6',
    sellerName: 'Bhaktapur Woodcraft',
    stock: 'low_stock',
    variants: [],
    tags: ['Handmade', 'Decor', 'Premium'],
    createdAt: daysAgo(60),
  },
  {
    id: 'prod-8',
    name: 'Xiaomi Redmi Note 13 Pro',
    slug: 'redmi-note-13-pro',
    description: '200MP camera, 120Hz AMOLED display, 5100mAh battery. Flagship features at a mid-range price.',
    images: [{ uri: 'https://picsum.photos/seed/redmi/400/400', alt: 'Redmi Note 13 Pro' }],
    price: 32999,
    compareAtPrice: 38999,
    currency: 'NPR',
    rating: 4.4,
    reviewCount: 167,
    categoryId: 'cat-phones',
    sellerId: 'seller-1',
    sellerName: 'TechHub Nepal',
    stock: 'in_stock',
    variants: [
      { id: 'v-8a', name: 'Midnight Black 128GB', price: 32999, sku: 'RED-13P-BLK', stock: 'in_stock', attributes: { color: 'Black', storage: '128GB' } },
      { id: 'v-8b', name: 'Ocean Teal 256GB', price: 37999, sku: 'RED-13P-TEL', stock: 'in_stock', attributes: { color: 'Teal', storage: '256GB' } },
    ],
    tags: ['5G', 'Xiaomi', 'Camera'],
    createdAt: daysAgo(15),
  },
  {
    id: 'prod-9',
    name: 'Singing Bowl — Hand Hammered',
    slug: 'singing-bowl-hand-hammered',
    description: 'Traditional hand-hammered singing bowl from Patan. Produces deep, resonant tones for meditation and healing.',
    images: [{ uri: 'https://picsum.photos/seed/bowl/400/400', alt: 'Singing bowl' }],
    price: 2800,
    currency: 'NPR',
    rating: 4.8,
    reviewCount: 203,
    categoryId: 'cat-home',
    sellerId: 'seller-7',
    sellerName: 'Patan Metal Works',
    stock: 'in_stock',
    variants: [
      { id: 'v-9a', name: 'Small (12cm)', price: 2800, sku: 'BOWL-SM', stock: 'in_stock', attributes: { size: '12cm' } },
      { id: 'v-9b', name: 'Medium (18cm)', price: 4500, sku: 'BOWL-MD', stock: 'in_stock', attributes: { size: '18cm' } },
      { id: 'v-9c', name: 'Large (25cm)', price: 7200, sku: 'BOWL-LG', stock: 'low_stock', attributes: { size: '25cm' } },
    ],
    tags: ['Handmade', 'Meditation', 'Cultural'],
    createdAt: daysAgo(180),
  },
  {
    id: 'prod-10',
    name: 'Timur Chilli Powder (200g)',
    slug: 'timur-chilli-powder',
    description: 'Sichuan pepper (timur) from the mid-hills of Nepal. Unique numbing citrus flavour essential for Nepali cooking.',
    images: [{ uri: 'https://picsum.photos/seed/timur/400/400', alt: 'Timur powder' }],
    price: 280,
    currency: 'NPR',
    rating: 4.5,
    reviewCount: 128,
    categoryId: 'cat-grocery',
    sellerId: 'seller-5',
    sellerName: 'Ilam Tea House',
    stock: 'in_stock',
    variants: [],
    tags: ['Spice', 'Organic', 'Nepali'],
    createdAt: daysAgo(100),
  },
]

export const deals: Deal[] = [
  { id: 'deal-1', title: 'Dashain Mega Sale', description: 'Up to 30% off on electronics', discount: 30, discountType: 'percentage', productId: 'prod-1', startsAt: daysAgo(2), endsAt: daysAgo(-5), image: 'https://picsum.photos/seed/deal1/800/300' },
  { id: 'deal-2', title: 'Handicraft Festival', description: 'Flat NPR 500 off on pashmina', discount: 500, discountType: 'fixed', productId: 'prod-4', startsAt: daysAgo(1), endsAt: daysAgo(-3), image: 'https://picsum.photos/seed/deal2/800/300' },
  { id: 'deal-3', title: 'Grocery Bundle', description: 'Buy 2 get 1 free on Wai Wai', discount: 33, discountType: 'percentage', productId: 'prod-3', startsAt: daysAgo(0), endsAt: daysAgo(-7), image: 'https://picsum.photos/seed/deal3/800/300' },
  { id: 'deal-4', title: 'Phone Fest', description: 'Redmi Note 13 Pro — NPR 6000 off', discount: 6000, discountType: 'fixed', productId: 'prod-8', startsAt: daysAgo(0), endsAt: daysAgo(-2), image: 'https://picsum.photos/seed/deal4/800/300' },
]

export const banners: Banner[] = [
  { id: 'ban-1', title: 'Dashain Sale is Live!', subtitle: 'Up to 50% off across categories', image: 'https://picsum.photos/seed/banner1/1200/400', link: '/deals', active: true },
  { id: 'ban-2', title: 'New Arrivals', subtitle: 'Check out the latest electronics', image: 'https://picsum.photos/seed/banner2/1200/400', link: '/categories/electronics', active: true },
  { id: 'ban-3', title: 'Free Delivery', subtitle: 'On orders above NPR 2000', image: 'https://picsum.photos/seed/banner3/1200/400', active: true },
]

export const reviews: Review[] = [
  { id: 'rev-1', productId: 'prod-1', userId: 'u-1', userName: 'Suman Shrestha', rating: 5, title: 'Best phone for the price', body: 'Camera quality is amazing. Battery lasts 2 days easily. Highly recommend!', photos: ['https://picsum.photos/seed/rev1a/200/200', 'https://picsum.photos/seed/rev1b/200/200'], createdAt: daysAgo(10), helpful: 24, sellerResponse: { text: 'Thank you so much for the kind review! We really appreciate your support. 🙏', at: daysAgo(9) } },
  { id: 'rev-2', productId: 'prod-1', userId: 'u-2', userName: 'Anita Gurung', rating: 4, body: 'Good phone but heats up a bit during gaming. Otherwise perfect.', createdAt: daysAgo(8), helpful: 12, sellerResponse: { text: 'Thanks for the feedback! We have noted the heating concern and are working with Samsung on it.', at: daysAgo(7) } },
  { id: 'rev-3', productId: 'prod-2', userId: 'u-3', userName: 'Ram Bahadur Thapa', rating: 5, title: 'Authentic quality', body: 'My grandfather loved this topi. The weaving is excellent — truly handmade.', photos: ['https://picsum.photos/seed/rev3a/200/200'], createdAt: daysAgo(45), helpful: 31, sellerResponse: { text: 'We are thrilled you loved it! Thank you for supporting local artisans. 🙏', at: daysAgo(44) } },
  { id: 'rev-4', productId: 'prod-4', userId: 'u-4', userName: 'Priya Maharjan', rating: 5, title: 'So soft!', body: 'Bought as a gift for my mother. She uses it every day. Worth every rupee.', createdAt: daysAgo(20), helpful: 18 },
  { id: 'rev-5', productId: 'prod-6', userId: 'u-5', userName: 'Karma Lama', rating: 4, body: 'Rich flavour. Reminds me of tea from my village. Will order again.', createdAt: daysAgo(15), helpful: 9 },
  { id: 'rev-6', productId: 'prod-1', userId: 'u-6', userName: 'Deepa Tamang', rating: 3, body: 'Decent phone for the price. Screen is great but speakers could be better.', createdAt: daysAgo(5), helpful: 4, sellerResponse: { text: 'Thank you for the honest feedback! We have passed your note about the speakers to our product team.', at: daysAgo(4) } },
  { id: 'rev-7', productId: 'prod-1', userId: 'u-7', userName: 'Rajesh Shrestha', rating: 5, title: 'Worth every rupee', body: 'Upgraded from A35. Night and day difference. The camera alone is worth it.', photos: ['https://picsum.photos/seed/rev7a/200/200', 'https://picsum.photos/seed/rev7b/200/200', 'https://picsum.photos/seed/rev7c/200/200'], createdAt: daysAgo(3), helpful: 7 },
]

export const addresses: Address[] = [
  { id: 'addr-1', label: 'Home', fullName: 'Ayush Chaudhary', phone: '+977-9841234567', line1: 'Baneshwor-10', line2: 'Near Shankar Dev Campus', city: 'Kathmandu', district: 'Kathmandu', province: 'Bagmati', postalCode: '44600', isDefault: true },
  { id: 'addr-2', label: 'Office', fullName: 'Ayush Chaudhary', phone: '+977-9841234567', line1: 'Thamel Marg', city: 'Kathmandu', district: 'Kathmandu', province: 'Bagmati', postalCode: '44600', isDefault: false },
]

export const orders: Order[] = [
  {
    id: 'ord-1',
    items: [
      { id: 'ci-1', productId: 'prod-1', variantId: 'v-1a', name: 'Samsung Galaxy A55 5G — Ice Blue 128GB', image: 'https://picsum.photos/seed/a55/400/400', price: 45999, quantity: 1, maxQuantity: 5 },
    ],
    total: 45999,
    currency: 'NPR',
    status: 'shipped',
    timeline: [
      { status: 'pending', timestamp: daysAgo(5) },
      { status: 'confirmed', timestamp: daysAgo(4) },
      { status: 'processing', timestamp: daysAgo(3) },
      { status: 'shipped', timestamp: daysAgo(1), note: 'Dispatched via Pathao' },
    ],
    address: addresses[0],
    createdAt: daysAgo(5),
    estimatedDelivery: daysAgo(-2),
  },
  {
    id: 'ord-2',
    items: [
      { id: 'ci-2', productId: 'prod-4', variantId: 'v-4a', name: 'Pashmina Shawl — Natural Cream', image: 'https://picsum.photos/seed/pashmina/400/400', price: 3500, quantity: 2, maxQuantity: 10 },
      { id: 'ci-3', productId: 'prod-6', variantId: 'v-6a', name: 'Masala Tea 250g', image: 'https://picsum.photos/seed/masala/400/400', price: 450, quantity: 3, maxQuantity: 20 },
    ],
    total: 8350,
    currency: 'NPR',
    status: 'delivered',
    timeline: [
      { status: 'pending', timestamp: daysAgo(20) },
      { status: 'confirmed', timestamp: daysAgo(19) },
      { status: 'processing', timestamp: daysAgo(18) },
      { status: 'shipped', timestamp: daysAgo(16) },
      { status: 'delivered', timestamp: daysAgo(14), note: 'Delivered to doorstep' },
    ],
    address: addresses[0],
    createdAt: daysAgo(20),
  },
  {
    id: 'ord-3',
    items: [
      { id: 'ci-4', productId: 'prod-2', variantId: 'v-2a', name: 'Dhaka Topi — Standard Red', image: 'https://picsum.photos/seed/topi/400/400', price: 850, quantity: 1, maxQuantity: 10 },
    ],
    total: 850,
    currency: 'NPR',
    status: 'pending',
    timeline: [
      { status: 'pending', timestamp: daysAgo(0) },
    ],
    address: addresses[0],
    createdAt: daysAgo(0),
  },
  {
    id: 'ord-4',
    items: [
      { id: 'ci-5', productId: 'prod-8', variantId: 'v-8b', name: 'Redmi Note 13 Pro — Ocean Teal 256GB', image: 'https://picsum.photos/seed/redmi/400/400', price: 37999, quantity: 1, maxQuantity: 3 },
    ],
    total: 37999,
    currency: 'NPR',
    status: 'confirmed',
    timeline: [
      { status: 'pending', timestamp: daysAgo(2) },
      { status: 'confirmed', timestamp: daysAgo(1), note: 'Payment verified via Khalti' },
    ],
    address: addresses[1],
    createdAt: daysAgo(2),
    estimatedDelivery: daysAgo(-3),
  },
  {
    id: 'ord-5',
    items: [
      { id: 'ci-6', productId: 'prod-9', variantId: 'v-9b', name: 'Singing Bowl — Medium 18cm', image: 'https://picsum.photos/seed/bowl/400/400', price: 4500, quantity: 1, maxQuantity: 5 },
      { id: 'ci-7', productId: 'prod-7', name: 'Wooden Mandala Wall Art', image: 'https://picsum.photos/seed/mandala/400/400', price: 4500, quantity: 1, maxQuantity: 3 },
    ],
    total: 9000,
    currency: 'NPR',
    status: 'processing',
    timeline: [
      { status: 'pending', timestamp: daysAgo(4) },
      { status: 'confirmed', timestamp: daysAgo(3) },
      { status: 'processing', timestamp: daysAgo(1), note: 'Seller is packing your order' },
    ],
    address: addresses[0],
    createdAt: daysAgo(4),
    estimatedDelivery: daysAgo(-1),
  },
  {
    id: 'ord-6',
    items: [
      { id: 'ci-8', productId: 'prod-3', name: 'Wai Wai Noodles (Pack of 40)', image: 'https://picsum.photos/seed/waiwai/400/400', price: 800, quantity: 2, maxQuantity: 20 },
    ],
    total: 1600,
    currency: 'NPR',
    status: 'cancelled',
    timeline: [
      { status: 'pending', timestamp: daysAgo(10) },
      { status: 'confirmed', timestamp: daysAgo(9) },
      { status: 'cancelled', timestamp: daysAgo(8), note: 'Cancelled by buyer' },
    ],
    address: addresses[0],
    createdAt: daysAgo(10),
  },
  {
    id: 'ord-7',
    items: [
      { id: 'ci-9', productId: 'prod-10', name: 'Timur Chilli Powder 200g', image: 'https://picsum.photos/seed/timur/400/400', price: 280, quantity: 5, maxQuantity: 30 },
      { id: 'ci-10', productId: 'prod-6', variantId: 'v-6b', name: 'Masala Tea 500g', image: 'https://picsum.photos/seed/masala/400/400', price: 800, quantity: 1, maxQuantity: 20 },
    ],
    total: 2200,
    currency: 'NPR',
    status: 'returned',
    timeline: [
      { status: 'pending', timestamp: daysAgo(30) },
      { status: 'confirmed', timestamp: daysAgo(29) },
      { status: 'processing', timestamp: daysAgo(28) },
      { status: 'shipped', timestamp: daysAgo(26) },
      { status: 'delivered', timestamp: daysAgo(24) },
      { status: 'returned', timestamp: daysAgo(20), note: 'Return accepted — refund processed' },
    ],
    address: addresses[0],
    createdAt: daysAgo(30),
  },
  {
    id: 'ord-8',
    items: [
      { id: 'ci-11', productId: 'prod-5', name: 'Daraz 10000mAh Power Bank', image: 'https://picsum.photos/seed/powerbank/400/400', price: 1299, quantity: 1, maxQuantity: 10 },
      { id: 'ci-12', productId: 'prod-4', variantId: 'v-4c', name: 'Pashmina Shawl — Black', image: 'https://picsum.photos/seed/pashmina/400/400', price: 3800, quantity: 1, maxQuantity: 10 },
    ],
    total: 5099,
    currency: 'NPR',
    status: 'delivered',
    timeline: [
      { status: 'pending', timestamp: daysAgo(45) },
      { status: 'confirmed', timestamp: daysAgo(44) },
      { status: 'processing', timestamp: daysAgo(43) },
      { status: 'shipped', timestamp: daysAgo(40) },
      { status: 'delivered', timestamp: daysAgo(38), note: 'Received by family member' },
    ],
    address: addresses[0],
    createdAt: daysAgo(45),
  },
]

export const notifications: Notification[] = [
  { id: 'notif-1', type: 'order', title: 'Order Shipped!', body: 'Your Samsung Galaxy A55 has been dispatched via Pathao.', read: false, createdAt: daysAgo(0), link: '/orders' },
  { id: 'notif-2', type: 'promo', title: 'Dashain Sale', body: 'Up to 50% off on electronics. Limited time only!', read: false, createdAt: daysAgo(0), link: '/deals' },
  { id: 'notif-5', type: 'price_drop', title: 'Price Drop Alert', body: 'Pashmina Shawl dropped from NPR 5,000 to NPR 3,500.', read: false, createdAt: daysAgo(0), link: '/product/pashmina-shawl-grade-a' },
  { id: 'notif-6', type: 'order', title: 'Order Confirmed', body: 'Your Redmi Note 13 Pro order has been confirmed. Payment verified via Khalti.', read: true, createdAt: daysAgo(1), link: '/orders' },
  { id: 'notif-7', type: 'promo', title: 'Free Delivery Weekend', body: 'Free delivery on all orders above NPR 1,000 this weekend!', read: true, createdAt: daysAgo(1), link: '/deals' },
  { id: 'notif-4', type: 'message', title: 'New message from TechHub Nepal', body: 'Your warranty card has been uploaded.', read: false, createdAt: daysAgo(3), link: '/inbox?tab=messages&thread=conv-1' },
  { id: 'notif-8', type: 'order', title: 'Order Delivered', body: 'Your Pashmina Shawl order was delivered. Rate your experience!', read: true, createdAt: daysAgo(5), link: '/orders' },
  { id: 'notif-9', type: 'price_drop', title: 'Price Drop Alert', body: 'Masala Tea 500g dropped to NPR 700. Save 12%!', read: true, createdAt: daysAgo(6), link: '/product/masala-tea-organic' },
  { id: 'notif-3', type: 'system', title: 'Welcome to Chinooz!', body: 'Explore thousands of products from local sellers.', read: true, createdAt: daysAgo(30) },
  { id: 'notif-10', type: 'system', title: 'App Update Available', body: 'Version 2.0 is here with faster checkout and new features.', read: true, createdAt: daysAgo(45) },
]

export const conversations: Conversation[] = [
  { id: 'conv-1', participantName: 'TechHub Nepal', participantAvatar: 'https://picsum.photos/seed/techhub/200/200', lastMessage: 'Your warranty card has been uploaded.', lastMessageAt: daysAgo(0), unreadCount: 2 },
  { id: 'conv-2', participantName: 'Nepal Handicrafts', lastMessage: 'Thank you for your order! We will ship within 24 hours.', lastMessageAt: daysAgo(1), unreadCount: 0 },
  { id: 'conv-3', participantName: 'Chinooz Support', lastMessage: 'How can we help you today?', lastMessageAt: daysAgo(3), unreadCount: 1 },
  { id: 'conv-4', participantName: 'Kathmandu Cashmere Co.', lastMessage: 'The black pashmina is back in stock!', lastMessageAt: daysAgo(5), unreadCount: 0 },
  { id: 'conv-5', participantName: 'Ilam Tea House', lastMessage: 'Your masala tea order has been dispatched.', lastMessageAt: daysAgo(8), unreadCount: 0 },
  { id: 'conv-6', participantName: 'Bhaktapur Woodcraft', lastMessage: 'We can customize the mandala size for you.', lastMessageAt: daysAgo(15), unreadCount: 0 },
]

export const messages: Message[] = [
  { id: 'msg-1', conversationId: 'conv-1', senderId: 'seller-1', senderName: 'TechHub Nepal', body: 'Hi! Your Samsung Galaxy A55 order has been confirmed.', createdAt: daysAgo(5), read: true, status: 'read' },
  { id: 'msg-2', conversationId: 'conv-1', senderId: 'user-1', senderName: 'You', body: 'Great, when will it ship?', createdAt: daysAgo(5), read: true, status: 'read' },
  { id: 'msg-3', conversationId: 'conv-1', senderId: 'seller-1', senderName: 'TechHub Nepal', body: 'It will ship within 24 hours. You will get a tracking link.', createdAt: daysAgo(4), read: true, status: 'read' },
  { id: 'msg-4', conversationId: 'conv-1', senderId: 'user-1', senderName: 'You', body: 'Perfect, thanks!', createdAt: daysAgo(4), read: true, status: 'read' },
  { id: 'msg-p', conversationId: 'conv-1', senderId: 'seller-1', senderName: 'TechHub Nepal', body: 'Also, check out this case — it pairs perfectly with your phone:', createdAt: daysAgo(3), read: true, status: 'read', productId: 'prod-5', productName: 'Daraz 10000mAh Power Bank', productImage: 'https://picsum.photos/seed/powerbank/400/400', productPrice: 1299 },
  { id: 'msg-5', conversationId: 'conv-1', senderId: 'user-1', senderName: 'You', body: 'Looks good! Does it come with a warranty?', createdAt: daysAgo(2), read: true, status: 'read' },
  { id: 'msg-6', conversationId: 'conv-1', senderId: 'seller-1', senderName: 'TechHub Nepal', body: 'Yes, 6 months warranty. Your warranty card has been uploaded.', createdAt: daysAgo(0), read: false, status: 'delivered' },
  { id: 'msg-7', conversationId: 'conv-1', senderId: 'seller-1', senderName: 'TechHub Nepal', body: 'Also, your phone case gift is on the way!', createdAt: daysAgo(0), read: false, status: 'delivered' },
  { id: 'msg-8', conversationId: 'conv-2', senderId: 'seller-2', senderName: 'Nepal Handicrafts', body: 'Thank you for your order! We will ship within 24 hours.', createdAt: daysAgo(1), read: true, status: 'read' },
  { id: 'msg-9', conversationId: 'conv-2', senderId: 'user-1', senderName: 'You', body: 'Can you gift wrap it?', createdAt: daysAgo(1), read: true, status: 'read' },
  { id: 'msg-10', conversationId: 'conv-2', senderId: 'seller-2', senderName: 'Nepal Handicrafts', body: 'Yes, we offer free gift wrapping! I will include a handwritten note as well.', createdAt: daysAgo(1), read: true, status: 'read' },
  { id: 'msg-11', conversationId: 'conv-3', senderId: 'system', senderName: 'Chinooz Support', body: 'How can we help you today?', createdAt: daysAgo(3), read: false, status: 'delivered' },
  { id: 'msg-12', conversationId: 'conv-4', senderId: 'seller-4', senderName: 'Kathmandu Cashmere Co.', body: 'The black pashmina is back in stock!', createdAt: daysAgo(5), read: true, status: 'read' },
  { id: 'msg-13', conversationId: 'conv-5', senderId: 'seller-5', senderName: 'Ilam Tea House', body: 'Your masala tea order has been dispatched.', createdAt: daysAgo(8), read: true, status: 'read' },
  { id: 'msg-14', conversationId: 'conv-6', senderId: 'seller-6', senderName: 'Bhaktapur Woodcraft', body: 'We can customize the mandala size for you. Would you like 30cm or 45cm?', createdAt: daysAgo(15), read: true, status: 'read' },
]

export const userProfile: UserProfile = {
  id: 'user-1',
  name: 'Ayush Chaudhary',
  email: 'ayush@example.com',
  phone: '+977-9841234567',
  defaultAddressId: 'addr-1',
  addresses,
}

export const sampleCartItems: CartItem[] = [
  { id: 'ci-s1', productId: 'prod-1', variantId: 'v-1a', name: 'Samsung Galaxy A55 5G — Ice Blue 128GB', image: 'https://picsum.photos/seed/a55/400/400', price: 45999, quantity: 1, maxQuantity: 5 },
  { id: 'ci-s2', productId: 'prod-4', variantId: 'v-4a', name: 'Pashmina Shawl — Natural Cream', image: 'https://picsum.photos/seed/pashmina/400/400', price: 3500, quantity: 2, maxQuantity: 10 },
  { id: 'ci-s3', productId: 'prod-6', variantId: 'v-6a', name: 'Masala Tea 250g', image: 'https://picsum.photos/seed/masala/400/400', price: 450, quantity: 1, maxQuantity: 20 },
]

export const sellerProducts: SellerProduct[] = [
  { id: 'sp-1', name: 'Samsung Galaxy A55 5G', sku: 'SAM-A55-BLU-128', image: 'https://picsum.photos/seed/a55/200/200', price: 45999, compareAtPrice: 52999, currency: 'NPR', categoryId: 'cat-phones', categoryName: 'Mobile Phones', stock: 'in_stock', stockCount: 38, status: 'active', salesCount: 234, viewsCount: 4820, rating: 4.5, reviewCount: 234, createdAt: daysAgo(30), updatedAt: daysAgo(3) },
  { id: 'sp-2', name: 'Handmade Dhaka Topi', sku: 'TOP-RED-STD', image: 'https://picsum.photos/seed/topi/200/200', price: 850, compareAtPrice: 1200, currency: 'NPR', categoryId: 'cat-mens', categoryName: "Men's Wear", stock: 'in_stock', stockCount: 120, status: 'active', salesCount: 512, viewsCount: 6210, rating: 4.8, reviewCount: 512, createdAt: daysAgo(120), updatedAt: daysAgo(12) },
  { id: 'sp-3', name: 'Wai Wai Noodles (Pack of 40)', sku: 'WAI-40-ORI', image: 'https://picsum.photos/seed/waiwai/200/200', price: 720, currency: 'NPR', categoryId: 'cat-snacks', categoryName: 'Snacks & Munchies', stock: 'in_stock', stockCount: 240, status: 'active', salesCount: 1890, viewsCount: 9120, rating: 4.6, reviewCount: 320, createdAt: daysAgo(60), updatedAt: daysAgo(1) },
  { id: 'sp-4', name: 'Pashmina Shawl — Natural Cream', sku: 'PSH-CRM-LRG', image: 'https://picsum.photos/seed/pashmina/200/200', price: 3500, compareAtPrice: 4200, currency: 'NPR', categoryId: 'cat-womens', categoryName: "Women's Wear", stock: 'low_stock', stockCount: 6, status: 'active', salesCount: 142, viewsCount: 3110, rating: 4.9, reviewCount: 98, createdAt: daysAgo(45), updatedAt: daysAgo(7) },
  { id: 'sp-5', name: 'Daraz 10000mAh Power Bank', sku: 'PWR-10K-BLK', image: 'https://picsum.photos/seed/powerbank/200/200', price: 1299, currency: 'NPR', categoryId: 'cat-audio', categoryName: 'Audio', stock: 'out_of_stock', stockCount: 0, status: 'out_of_stock', salesCount: 76, viewsCount: 1450, rating: 4.2, reviewCount: 41, createdAt: daysAgo(22), updatedAt: daysAgo(2) },
  { id: 'sp-6', name: 'Ilam Masala Tea 250g', sku: 'TEA-MAS-250', image: 'https://picsum.photos/seed/masala/200/200', price: 450, currency: 'NPR', categoryId: 'cat-beverages', categoryName: 'Beverages', stock: 'in_stock', stockCount: 320, status: 'active', salesCount: 2400, viewsCount: 8800, rating: 4.7, reviewCount: 410, createdAt: daysAgo(75), updatedAt: daysAgo(1) },
  { id: 'sp-7', name: 'Bhaktapur Carved Wooden Mandala', sku: 'WD-MDL-30', image: 'https://picsum.photos/seed/mandala/200/200', price: 2800, currency: 'NPR', categoryId: 'cat-furniture', categoryName: 'Furniture', stock: 'low_stock', stockCount: 3, status: 'active', salesCount: 28, viewsCount: 980, rating: 4.9, reviewCount: 19, createdAt: daysAgo(90), updatedAt: daysAgo(15) },
  { id: 'sp-8', name: 'Wireless Earbuds Pro', sku: 'AUD-EAR-PRO', image: 'https://picsum.photos/seed/earbuds/200/200', price: 2499, compareAtPrice: 2999, currency: 'NPR', categoryId: 'cat-audio', categoryName: 'Audio', stock: 'in_stock', stockCount: 54, status: 'active', salesCount: 320, viewsCount: 5200, rating: 4.3, reviewCount: 180, createdAt: daysAgo(18), updatedAt: daysAgo(4) },
  { id: 'sp-9', name: 'Stainless Steel Cookware Set', sku: 'KCH-SET-5', image: 'https://picsum.photos/seed/cookware/200/200', price: 4200, currency: 'NPR', categoryId: 'cat-kitchen', categoryName: 'Kitchen', stock: 'in_stock', stockCount: 22, status: 'active', salesCount: 64, viewsCount: 1320, rating: 4.4, reviewCount: 33, createdAt: daysAgo(40), updatedAt: daysAgo(9) },
  { id: 'sp-10', name: 'Organic Honey 500ml', sku: 'HNY-500-ORG', image: 'https://picsum.photos/seed/honey/200/200', price: 620, currency: 'NPR', categoryId: 'cat-grocery', categoryName: 'Grocery', stock: 'in_stock', stockCount: 180, status: 'active', salesCount: 540, viewsCount: 4100, rating: 4.8, reviewCount: 220, createdAt: daysAgo(50), updatedAt: daysAgo(2) },
  { id: 'sp-11', name: 'Acer Aspire Lite Laptop', sku: 'LAP-ASP-LITE', image: 'https://picsum.photos/seed/laptop/200/200', price: 64999, currency: 'NPR', categoryId: 'cat-laptops', categoryName: 'Laptops', stock: 'out_of_stock', stockCount: 0, status: 'out_of_stock', salesCount: 12, viewsCount: 880, rating: 4.1, reviewCount: 9, createdAt: daysAgo(14), updatedAt: daysAgo(1) },
  { id: 'sp-12', name: 'Cotton Kurta — Indigo', sku: 'KRT-IND-MED', image: 'https://picsum.photos/seed/kurta/200/200', price: 1450, currency: 'NPR', categoryId: 'cat-mens', categoryName: "Men's Wear", stock: 'in_stock', stockCount: 76, status: 'draft', salesCount: 0, viewsCount: 0, rating: 0, reviewCount: 0, createdAt: daysAgo(2), updatedAt: daysAgo(2) },
  { id: 'sp-13', name: 'Ayurvedic Face Wash 100ml', sku: 'BTY-FW-100', image: 'https://picsum.photos/seed/facewash/200/200', price: 380, currency: 'NPR', categoryId: 'cat-beauty', categoryName: 'Beauty & Health', stock: 'in_stock', stockCount: 260, status: 'active', salesCount: 1120, viewsCount: 7300, rating: 4.5, reviewCount: 305, createdAt: daysAgo(35), updatedAt: daysAgo(3) },
  { id: 'sp-14', name: 'Yoga Mat Premium 6mm', sku: 'SPT-YGA-6', image: 'https://picsum.photos/seed/yogamat/200/200', price: 980, currency: 'NPR', categoryId: 'cat-sports', categoryName: 'Sports & Outdoors', stock: 'low_stock', stockCount: 8, status: 'active', salesCount: 96, viewsCount: 1740, rating: 4.4, reviewCount: 52, createdAt: daysAgo(28), updatedAt: daysAgo(6) },
  { id: 'sp-15', name: 'Handwoven Wool Muffler', sku: 'ACC-MUF-WOL', image: 'https://picsum.photos/seed/muffler/200/200', price: 1100, currency: 'NPR', categoryId: 'cat-womens', categoryName: "Women's Wear", stock: 'in_stock', stockCount: 44, status: 'draft', salesCount: 0, viewsCount: 0, rating: 0, reviewCount: 0, createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: 'sp-16', name: 'Ceramic Tea Cup Set (6)', sku: 'KCH-CUP-6', image: 'https://picsum.photos/seed/teacups/200/200', price: 1650, currency: 'NPR', categoryId: 'cat-kitchen', categoryName: 'Kitchen', stock: 'in_stock', stockCount: 30, status: 'archived', salesCount: 210, viewsCount: 2600, rating: 4.6, reviewCount: 88, createdAt: daysAgo(200), updatedAt: daysAgo(80) },
  { id: 'sp-17', name: 'Bluetooth Speaker Mini', sku: 'AUD-SPK-MIN', image: 'https://picsum.photos/seed/speaker/200/200', price: 1899, currency: 'NPR', categoryId: 'cat-audio', categoryName: 'Audio', stock: 'in_stock', stockCount: 41, status: 'active', salesCount: 188, viewsCount: 3400, rating: 4.2, reviewCount: 73, createdAt: daysAgo(20), updatedAt: daysAgo(5) },
  { id: 'sp-18', name: 'Khukuri Display Replica', sku: 'HDK-KHK-RPL', image: 'https://picsum.photos/seed/khukuri/200/200', price: 3200, currency: 'NPR', categoryId: 'cat-home', categoryName: 'Home & Kitchen', stock: 'low_stock', stockCount: 4, status: 'archived', salesCount: 31, viewsCount: 1120, rating: 4.7, reviewCount: 22, createdAt: daysAgo(160), updatedAt: daysAgo(70) },
  { id: 'sp-19', name: 'LED Desk Lamp Dimmable', sku: 'HME-LMP-LED', image: 'https://picsum.photos/seed/desklamp/200/200', price: 1450, currency: 'NPR', categoryId: 'cat-home', categoryName: 'Home & Kitchen', stock: 'in_stock', stockCount: 65, status: 'active', salesCount: 142, viewsCount: 2900, rating: 4.5, reviewCount: 61, createdAt: daysAgo(25), updatedAt: daysAgo(4) },
  { id: 'sp-20', name: 'Trail Running Shoes', sku: 'SPT-SHO-TRR', image: 'https://picsum.photos/seed/shoes/200/200', price: 3800, compareAtPrice: 4400, currency: 'NPR', categoryId: 'cat-sports', categoryName: 'Sports & Outdoors', stock: 'in_stock', stockCount: 27, status: 'active', salesCount: 84, viewsCount: 2050, rating: 4.3, reviewCount: 37, createdAt: daysAgo(33), updatedAt: daysAgo(8) },
]

export const sellerConversations: Conversation[] = [
  {
    id: 'sconv-1',
    participantName: 'Aarav Shrestha',
    participantAvatar: 'https://picsum.photos/seed/aarav/200/200',
    lastMessage: 'Is the Samsung Galaxy A55 still in stock? I need it by Friday.',
    lastMessageAt: daysAgo(0),
    unreadCount: 3,
    contextType: 'product',
    productId: 'sp-1',
    productName: 'Samsung Galaxy A55 5G',
  },
  {
    id: 'sconv-2',
    participantName: 'Sita Gurung',
    participantAvatar: 'https://picsum.photos/seed/sita/200/200',
    lastMessage: 'Where is my order? It has been 3 days already.',
    lastMessageAt: daysAgo(0),
    unreadCount: 1,
    contextType: 'order',
    orderId: 'ord-1',
    orderRef: '#ORD-2051',
  },
  {
    id: 'sconv-3',
    participantName: 'Bishal Thapa',
    participantAvatar: 'https://picsum.photos/seed/bishal/200/200',
    lastMessage: 'Thank you! The pashmina arrived and it is beautiful.',
    lastMessageAt: daysAgo(1),
    unreadCount: 0,
    contextType: 'order',
    orderId: 'ord-2',
    orderRef: '#ORD-2048',
  },
  {
    id: 'sconv-4',
    participantName: 'Priya Maharjan',
    participantAvatar: 'https://picsum.photos/seed/priya/200/200',
    lastMessage: 'Do you have the Dhaka Topi in red? My father wants one.',
    lastMessageAt: daysAgo(2),
    unreadCount: 2,
    contextType: 'product',
    productId: 'sp-2',
    productName: 'Handmade Dhaka Topi',
  },
  {
    id: 'sconv-5',
    participantName: 'Rohan Tamang',
    participantAvatar: 'https://picsum.photos/seed/rohan/200/200',
    lastMessage: 'Can I get a bulk discount on 20 packs of Wai Wai?',
    lastMessageAt: daysAgo(3),
    unreadCount: 0,
    contextType: 'product',
    productId: 'sp-3',
    productName: 'Wai Wai Noodles (Pack of 40)',
  },
  {
    id: 'sconv-6',
    participantName: 'Anjali K.C.',
    participantAvatar: 'https://picsum.photos/seed/anjali/200/200',
    lastMessage: 'The power bank I received is not charging. Need a replacement.',
    lastMessageAt: daysAgo(4),
    unreadCount: 0,
    contextType: 'order',
    orderId: 'ord-1',
    orderRef: '#ORD-2042',
  },
  {
    id: 'sconv-7',
    participantName: 'Chinooz Support',
    participantAvatar: 'https://picsum.photos/seed/support/200/200',
    lastMessage: 'A buyer has opened a return request for order #ORD-2048.',
    lastMessageAt: daysAgo(5),
    unreadCount: 0,
    contextType: 'general',
  },
  {
    id: 'sconv-8',
    participantName: 'Kiran Rai',
    participantAvatar: 'https://picsum.photos/seed/kiran/200/200',
    lastMessage: 'Got it, thanks for the quick reply!',
    lastMessageAt: daysAgo(9),
    unreadCount: 0,
    contextType: 'general',
  },
]

export const sellerMessages: Message[] = [
  { id: 'smsg-1', conversationId: 'sconv-1', senderId: 'buyer-aarav', senderName: 'Aarav Shrestha', body: 'Hi! Is the Samsung Galaxy A55 still in stock?', createdAt: daysAgo(0), read: false, status: 'delivered' },
  { id: 'smsg-2', conversationId: 'sconv-1', senderId: 'buyer-aarav', senderName: 'Aarav Shrestha', body: 'I need it by Friday for a gift.', createdAt: daysAgo(0), read: false, status: 'delivered' },
  { id: 'smsg-3', conversationId: 'sconv-1', senderId: 'buyer-aarav', senderName: 'Aarav Shrestha', body: 'Is the Samsung Galaxy A55 still in stock? I need it by Friday.', createdAt: daysAgo(0), read: false, status: 'delivered' },
  { id: 'smsg-4', conversationId: 'sconv-2', senderId: 'buyer-sita', senderName: 'Sita Gurung', body: 'Where is my order? It has been 3 days already.', createdAt: daysAgo(0), read: false, status: 'delivered' },
  { id: 'smsg-5', conversationId: 'sconv-3', senderId: 'buyer-bishal', senderName: 'Bishal Thapa', body: 'Thank you! The pashmina arrived and it is beautiful.', createdAt: daysAgo(1), read: true, status: 'read' },
  { id: 'smsg-6', conversationId: 'sconv-3', senderId: 'seller-1', senderName: 'You', body: 'So glad you love it! Please leave a review if you have a moment.', createdAt: daysAgo(1), read: true, status: 'read' },
  { id: 'smsg-7', conversationId: 'sconv-4', senderId: 'buyer-priya', senderName: 'Priya Maharjan', body: 'Do you have the Dhaka Topi in red?', createdAt: daysAgo(2), read: false, status: 'delivered' },
  { id: 'smsg-8', conversationId: 'sconv-4', senderId: 'buyer-priya', senderName: 'Priya Maharjan', body: 'My father wants one for Dashain.', createdAt: daysAgo(2), read: false, status: 'delivered' },
  { id: 'smsg-9', conversationId: 'sconv-5', senderId: 'buyer-rohan', senderName: 'Rohan Tamang', body: 'Can I get a bulk discount on 20 packs of Wai Wai?', createdAt: daysAgo(3), read: true, status: 'read' },
  { id: 'smsg-10', conversationId: 'sconv-6', senderId: 'buyer-anjali', senderName: 'Anjali K.C.', body: 'The power bank I received is not charging. Need a replacement.', createdAt: daysAgo(4), read: true, status: 'read' },
  { id: 'smsg-11', conversationId: 'sconv-7', senderId: 'system', senderName: 'Chinooz Support', body: 'A buyer has opened a return request for order #ORD-2048.', createdAt: daysAgo(5), read: true, status: 'read' },
  { id: 'smsg-12', conversationId: 'sconv-8', senderId: 'buyer-kiran', senderName: 'Kiran Rai', body: 'Got it, thanks for the quick reply!', createdAt: daysAgo(9), read: true, status: 'read' },
]
