import type { Product } from '@chinooz/types'

export const products: Product[] = [
  {
    id: 'prod-1',
    slug: 'samsung-galaxy-s24',
    name: 'Samsung Galaxy S24 Ultra 5G',
    nameNe: 'सामसुङ ग्यालेक्सी S24 अल्ट्रा 5G',
    description:
      'Flagship smartphone with 200MP camera, S Pen, and Galaxy AI features. 12GB RAM, 256GB storage.',
    descriptionNe:
      '200MP क्यामेरा, S पेन र ग्यालेक्सी AI सुविधाहरू सहितको फ्ल्यागशिप स्मार्टफोन। १२GB RAM, २५६GB स्टोरेज।',
    price: 159999,
    compareAtPrice: 179999,
    images: [
      'https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=400',
      'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400',
    ],
    categoryId: 'cat-1',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    categoryNameNe: 'इलेक्ट्रोनिक्स',
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    stockCount: 45,
    sellerId: 'seller-1',
    sellerName: 'TechZone Nepal',
    brand: 'Samsung',
    tags: ['smartphone', '5g', 'android', 'samsung'],
    isDeal: true,
    dealPercent: 11,
    dealEndsAt: '2026-07-05T23:59:59Z',
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'prod-2',
    slug: 'iphone-15-pro',
    name: 'Apple iPhone 15 Pro Max 256GB',
    nameNe: 'एप्पल आइफोन 15 प्रो म्याक्स २५६GB',
    description:
      'A17 Pro chip, 48MP camera system, titanium design, and USB-C.',
    price: 199999,
    compareAtPrice: 219999,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400',
    ],
    categoryId: 'cat-1',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    stockCount: 22,
    sellerId: 'seller-2',
    sellerName: 'iStore Nepal',
    brand: 'Apple',
    tags: ['smartphone', '5g', 'ios', 'apple'],
    createdAt: '2026-05-15T00:00:00Z',
  },
  {
    id: 'prod-3',
    slug: 'nike-air-max',
    name: 'Nike Air Max 270 React',
    nameNe: 'नाइक एयर म्याक्स २७० रिएक्ट',
    description:
      'Comfortable lifestyle sneaker with large Air unit and React foam.',
    price: 18500,
    compareAtPrice: 22500,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    ],
    categoryId: 'cat-2',
    categorySlug: 'fashion',
    categoryName: 'Fashion',
    rating: 4.5,
    reviewCount: 89,
    inStock: true,
    stockCount: 120,
    sellerId: 'seller-3',
    sellerName: 'KickStreet Nepal',
    brand: 'Nike',
    tags: ['shoes', 'sneakers', 'nike', 'fashion'],
    createdAt: '2026-05-20T00:00:00Z',
  },
  {
    id: 'prod-4',
    slug: 'basmati-rice',
    name: 'Premium Basmati Rice - 5kg',
    nameNe: 'प्रिमियम बासमती चामल - ५ किलो',
    description: 'Long grain basmati rice from Jhapa, perfect for biryani and pulao.',
    price: 875,
    images: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    ],
    categoryId: 'cat-3',
    categorySlug: 'groceries',
    categoryName: 'Groceries',
    rating: 4.3,
    reviewCount: 567,
    inStock: true,
    stockCount: 500,
    sellerId: 'seller-4',
    sellerName: 'Himalayan Grocers',
    tags: ['rice', 'basmati', 'grocery', 'staples'],
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'prod-5',
    slug: 'dabur-chyawanprash',
    name: 'Dabur Chyawanprash 1kg',
    nameNe: 'डाबर च्यवनप्राश १ किलो',
    description: 'Ayurvedic health supplement with vitamin C, 45+ herbs.',
    price: 645,
    compareAtPrice: 750,
    images: [
      'https://images.unsplash.com/photo-1616671276441-2f2c277b8bf6?w=400',
    ],
    categoryId: 'cat-5',
    categorySlug: 'beauty-health',
    categoryName: 'Beauty & Health',
    rating: 4.4,
    reviewCount: 1234,
    inStock: true,
    stockCount: 300,
    sellerId: 'seller-5',
    sellerName: 'HealthFirst',
    brand: 'Dabur',
    tags: ['health', 'supplement', 'ayurvedic'],
    createdAt: '2026-05-01T00:00:00Z',
  },
  {
    id: 'prod-6',
    slug: 'macbook-air-m3',
    name: 'Apple MacBook Air M3 15-inch',
    description: '15.3-inch Liquid Retina display, M3 chip, 16GB RAM, 512GB SSD.',
    price: 189999,
    compareAtPrice: 209999,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400',
    ],
    categoryId: 'cat-1',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    stockCount: 18,
    sellerId: 'seller-2',
    sellerName: 'iStore Nepal',
    brand: 'Apple',
    tags: ['laptop', 'apple', 'm3', 'macbook'],
    createdAt: '2026-05-10T00:00:00Z',
  },
  {
    id: 'prod-7',
    slug: 'pashmina-shawl',
    name: 'Handwoven Pashmina Shawl',
    nameNe: 'हातले बुनेको पश्मिना सल',
    description: 'Authentic Nepali pashmina shawl, handwoven in Pokhara. Soft, warm, and elegant.',
    price: 4500,
    compareAtPrice: 6500,
    images: [
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400',
    ],
    categoryId: 'cat-2',
    categorySlug: 'fashion',
    categoryName: 'Fashion',
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    stockCount: 55,
    sellerId: 'seller-6',
    sellerName: 'Nepali Crafts',
    tags: ['pashmina', 'shawl', 'handwoven', 'nepali'],
    createdAt: '2026-03-15T00:00:00Z',
  },
  {
    id: 'prod-8',
    slug: 'kitchen-knife-set',
    name: 'Professional Kitchen Knife Set - 6 Pieces',
    description: 'Stainless steel chef knife set with wooden block. Includes chef, bread, utility, and paring knives.',
    price: 3200,
    compareAtPrice: 4500,
    images: [
      'https://images.unsplash.com/photo-1563861826100-9cb8680ae1e7?w=400',
    ],
    categoryId: 'cat-4',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    rating: 4.2,
    reviewCount: 73,
    inStock: true,
    stockCount: 88,
    sellerId: 'seller-7',
    sellerName: 'Home Essentials NP',
    tags: ['kitchen', 'knife', 'cooking'],
    createdAt: '2026-04-20T00:00:00Z',
  },
  {
    id: 'prod-9',
    slug: 'yoga-mat',
    name: 'Premium Extra Thick Yoga Mat - 6mm',
    description: 'Non-slip, eco-friendly TPE yoga mat with carrying strap.',
    price: 2200,
    compareAtPrice: 2800,
    images: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400',
    ],
    categoryId: 'cat-6',
    categorySlug: 'sports',
    categoryName: 'Sports & Outdoors',
    rating: 4.6,
    reviewCount: 145,
    inStock: true,
    stockCount: 200,
    sellerId: 'seller-8',
    sellerName: 'FitNepal',
    tags: ['yoga', 'fitness', 'mat', 'exercise'],
    createdAt: '2026-05-05T00:00:00Z',
  },
  {
    id: 'prod-10',
    slug: 'nepali-dal-mix',
    name: 'Mixed Dal Pack - 5 Types, 1kg Each',
    description: 'Masoor, moong, toor, chana, and urad dal. Premium quality sourced from Nepali farms.',
    price: 680,
    images: [
      'https://images.unsplash.com/photo-1519735777090-ec97162dc266?w=400',
    ],
    categoryId: 'cat-3',
    categorySlug: 'groceries',
    categoryName: 'Groceries',
    rating: 4.1,
    reviewCount: 432,
    inStock: true,
    stockCount: 600,
    sellerId: 'seller-4',
    sellerName: 'Himalayan Grocers',
    tags: ['dal', 'pulses', 'grocery', 'staples'],
    createdAt: '2026-04-10T00:00:00Z',
  },
  {
    id: 'prod-11',
    slug: 'wireless-earbuds',
    name: 'Sony WF-1000XM5 Wireless Earbuds',
    description: 'Industry-leading noise cancellation, Hi-Res Audio, 8hr battery.',
    price: 32000,
    compareAtPrice: 38000,
    images: [
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400',
    ],
    categoryId: 'cat-1',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    rating: 4.7,
    reviewCount: 201,
    inStock: true,
    stockCount: 34,
    sellerId: 'seller-1',
    sellerName: 'TechZone Nepal',
    brand: 'Sony',
    tags: ['earbuds', 'audio', 'wireless', 'sony'],
    isDeal: true,
    dealPercent: 16,
    dealEndsAt: '2026-07-03T23:59:59Z',
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'prod-12',
    slug: 'men-leather-wallet',
    name: 'Genuine Leather Bifold Wallet',
    description: 'Handcrafted full-grain leather wallet with RFID blocking. 8 card slots.',
    price: 1600,
    compareAtPrice: 2200,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400',
    ],
    categoryId: 'cat-2',
    categorySlug: 'fashion',
    categoryName: 'Fashion',
    rating: 4.4,
    reviewCount: 67,
    inStock: true,
    stockCount: 150,
    sellerId: 'seller-6',
    sellerName: 'Nepali Crafts',
    tags: ['wallet', 'leather', 'accessories'],
    createdAt: '2026-05-25T00:00:00Z',
  },
  {
    id: 'prod-13',
    slug: 'baby-diapers',
    name: 'Huggies Diapers - Large Pack (84 pcs)',
    description: 'Ultra-soft, super absorbent diapers for babies 9-14kg.',
    price: 1850,
    compareAtPrice: 2100,
    images: [
      'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=400',
    ],
    categoryId: 'cat-8',
    categorySlug: 'baby-kids',
    categoryName: 'Baby & Kids',
    rating: 4.5,
    reviewCount: 890,
    inStock: true,
    stockCount: 250,
    sellerId: 'seller-9',
    sellerName: 'BabyCare Nepal',
    brand: 'Huggies',
    tags: ['diapers', 'baby', 'huggies'],
    createdAt: '2026-05-01T00:00:00Z',
  },
  {
    id: 'prod-14',
    slug: 'electric-kettle',
    name: 'Philips Electric Kettle 1.5L',
    description: 'Stainless steel, 2200W, auto shut-off, boil-dry protection.',
    price: 2100,
    compareAtPrice: 2800,
    images: [
      'https://images.unsplash.com/photo-1574226516838-bfa6d57a0b11?w=400',
    ],
    categoryId: 'cat-4',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    rating: 4.3,
    reviewCount: 345,
    inStock: true,
    stockCount: 180,
    sellerId: 'seller-7',
    sellerName: 'Home Essentials NP',
    brand: 'Philips',
    tags: ['kettle', 'kitchen', 'appliance', 'philips'],
    isDeal: true,
    dealPercent: 25,
    dealEndsAt: '2026-07-02T23:59:59Z',
    createdAt: '2026-06-05T00:00:00Z',
  },
  {
    id: 'prod-15',
    slug: 'atomic-habits-book',
    name: 'Atomic Habits - James Clear',
    description: 'The #1 New York Times bestseller. Practical guide to building good habits and breaking bad ones.',
    price: 699,
    images: [
      'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400',
    ],
    categoryId: 'cat-7',
    categorySlug: 'books-stationery',
    categoryName: 'Books & Stationery',
    rating: 4.8,
    reviewCount: 2100,
    inStock: true,
    stockCount: 400,
    sellerId: 'seller-10',
    sellerName: 'BookMandala',
    tags: ['book', 'self-help', 'habits', 'bestseller'],
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'prod-16',
    slug: 'bike-helmet',
    name: 'Steelbird Full Face Bike Helmet',
    description: 'ISI certified, scratch-resistant visor, ventilated, quick-release buckle.',
    price: 3500,
    compareAtPrice: 4500,
    images: [
      'https://images.unsplash.com/photo-1558981359-21502c7f57c8?w=400',
    ],
    categoryId: 'cat-9',
    categorySlug: 'automotive',
    categoryName: 'Automotive',
    rating: 4.2,
    reviewCount: 178,
    inStock: true,
    stockCount: 75,
    sellerId: 'seller-11',
    sellerName: 'AutoGear Nepal',
    brand: 'Steelbird',
    tags: ['helmet', 'bike', 'safety', 'automotive'],
    createdAt: '2026-04-15T00:00:00Z',
  },
  {
    id: 'prod-17',
    slug: 'silver-earrings',
    name: 'Nepali Silver Drop Earrings - Handcrafted',
    description: 'Sterling silver (925) traditional drop earrings. Handmade by artisans in Patan.',
    price: 2800,
    compareAtPrice: 3500,
    images: [
      'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=400',
    ],
    categoryId: 'cat-10',
    categorySlug: 'jewelry',
    categoryName: 'Jewelry & Accessories',
    rating: 4.7,
    reviewCount: 56,
    inStock: true,
    stockCount: 40,
    sellerId: 'seller-6',
    sellerName: 'Nepali Crafts',
    tags: ['earrings', 'silver', 'handcrafted', 'nepali'],
    createdAt: '2026-05-10T00:00:00Z',
  },
  {
    id: 'prod-18',
    slug: 'protein-powder',
    name: 'MuscleBlaze Whey Protein 2kg - Chocolate',
    description: '26g protein per serving, 100% whey protein isolate, rich chocolate flavor.',
    price: 4500,
    compareAtPrice: 5500,
    images: [
      'https://images.unsplash.com/photo-1593095948071-474c5cc2c1cf?w=400',
    ],
    categoryId: 'cat-5',
    categorySlug: 'beauty-health',
    categoryName: 'Beauty & Health',
    rating: 4.4,
    reviewCount: 267,
    inStock: true,
    stockCount: 90,
    sellerId: 'seller-5',
    sellerName: 'HealthFirst',
    brand: 'MuscleBlaze',
    tags: ['protein', 'whey', 'supplement', 'fitness'],
    createdAt: '2026-05-20T00:00:00Z',
  },
  {
    id: 'prod-19',
    slug: 'samsung-65-tv',
    name: 'Samsung 65" Crystal UHD 4K Smart TV',
    description: 'Crystal Processor 4K, HDR, Dolby Digital Plus, Smart Hub.',
    price: 129999,
    compareAtPrice: 159999,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400',
    ],
    categoryId: 'cat-1',
    categorySlug: 'electronics',
    categoryName: 'Electronics',
    rating: 4.5,
    reviewCount: 98,
    inStock: true,
    stockCount: 12,
    sellerId: 'seller-1',
    sellerName: 'TechZone Nepal',
    brand: 'Samsung',
    tags: ['tv', '4k', 'samsung', 'smart-tv'],
    isDeal: true,
    dealPercent: 19,
    dealEndsAt: '2026-07-01T23:59:59Z',
    createdAt: '2026-06-10T00:00:00Z',
  },
  {
    id: 'prod-20',
    slug: 'wooden-coffee-table',
    name: 'Sheesham Wood Coffee Table',
    description: 'Solid sheesham wood coffee table with storage shelf. Natural finish, handcrafted in Nepal.',
    price: 12500,
    compareAtPrice: 16000,
    images: [
      'https://images.unsplash.com/photo-1532372576444-dda954194ad0?w=400',
    ],
    categoryId: 'cat-4',
    categorySlug: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    rating: 4.6,
    reviewCount: 34,
    inStock: true,
    stockCount: 15,
    sellerId: 'seller-12',
    sellerName: 'Woodcraft Nepal',
    tags: ['furniture', 'table', 'coffee-table', 'wood'],
    createdAt: '2026-05-01T00:00:00Z',
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter(p => p.categorySlug === categorySlug)
}

export function getDealProducts(): Product[] {
  return products.filter(p => p.isDeal)
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase()
  return products.filter(
    p =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some(t => t.toLowerCase().includes(q)) ||
      p.brand?.toLowerCase().includes(q),
  )
}
