import type { Review } from '@chinooz/types'

export const reviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    userId: 'user-1',
    userName: 'Rajesh Hamal',
    rating: 5,
    title: 'Amazing phone!',
    comment: 'Best camera I have ever used. The S Pen is incredibly useful for notes. Battery lasts all day.',
    createdAt: '2026-06-10T12:00:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    userId: 'user-2',
    userName: 'Sita Sharma',
    rating: 4,
    title: 'Great but heavy',
    comment: 'Performance is top notch. Camera quality is insane. Only downside is the weight - it is quite heavy.',
    createdAt: '2026-06-08T09:30:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-3',
    userId: 'user-3',
    userName: 'Binod Thapa',
    rating: 5,
    title: 'Super comfortable',
    comment: 'Most comfortable sneakers I have ever worn. Looks great too. Worth every penny.',
    createdAt: '2026-06-05T14:00:00Z',
  },
  {
    id: 'rev-4',
    productId: 'prod-4',
    userId: 'user-4',
    userName: 'Gita Adhikari',
    rating: 4,
    title: 'Good quality rice',
    comment: 'The rice is aromatic and cooks well. Good value for money at this price.',
    createdAt: '2026-05-20T10:00:00Z',
  },
  {
    id: 'rev-5',
    productId: 'prod-7',
    userId: 'user-5',
    userName: 'Anita Gurung',
    rating: 5,
    title: 'Exquisite craftsmanship',
    comment: 'This pashmina is incredibly soft and warm. The handwoven detail is beautiful. Perfect gift.',
    createdAt: '2026-05-18T16:00:00Z',
  },
  {
    id: 'rev-6',
    productId: 'prod-9',
    userId: 'user-6',
    userName: 'Sagar Poudel',
    rating: 4,
    title: 'Good yoga mat',
    comment: 'Nice thickness, good grip. Does not slip even during sweaty sessions. Recommended.',
    createdAt: '2026-06-12T08:00:00Z',
  },
  {
    id: 'rev-7',
    productId: 'prod-15',
    userId: 'user-7',
    userName: 'Prakash Neupane',
    rating: 5,
    title: 'Life-changing book',
    comment: 'This book completely changed my perspective on habits. Simple, actionable advice. A must-read.',
    createdAt: '2026-04-01T11:00:00Z',
  },
  {
    id: 'rev-8',
    productId: 'prod-14',
    userId: 'user-8',
    userName: 'Maya Rai',
    rating: 4,
    title: 'Good kettle',
    comment: 'Works well, boils water quickly. Looks sleek on the counter. Good value.',
    createdAt: '2026-06-18T15:00:00Z',
  },
]

export function getReviewsByProduct(productId: string): Review[] {
  return reviews.filter(r => r.productId === productId)
}
